'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import {
  Zap, Plus, Trash2, RefreshCw, ChevronRight,
  Copy, Check, Target, Users, Calendar, BarChart2, Download,
  Pencil, BookmarkPlus,
} from 'lucide-react'
import { toast } from 'sonner'
import { useAppStore } from '@/stores/app-store'
import { api } from '@/lib/api'
import type { Campaign, CampaignContentPack } from '@/types'
import { cn } from '@/lib/utils'
import { SidebarToggle } from '@/components/layout/sidebar'

// ---------------------------------------------------------------------------
// Channel display helpers
// ---------------------------------------------------------------------------

const CHANNEL_LABELS: Record<string, string> = {
  instagram: 'Instagram', linkedin: 'LinkedIn', twitter: 'X / Twitter',
  tiktok: 'TikTok', meta_ads: 'Meta Ads', google_ads: 'Google Ads', email: 'Email',
}
const CHANNEL_ICONS: Record<string, string> = {
  instagram: '📸', linkedin: '💼', twitter: '𝕏', tiktok: '🎵',
  meta_ads: '📢', google_ads: '🔍', email: '✉️',
}

// ---------------------------------------------------------------------------
// Export helper
// ---------------------------------------------------------------------------

function buildCampaignMarkdown(campaign: Campaign): string {
  const brief = campaign.brief
  const packs = campaign.contentPacks ?? {}
  const lines: string[] = []

  lines.push(`# ${campaign.name}`, '')
  lines.push(`> Generated by LEO · ${new Date(campaign.createdAt).toLocaleDateString()}`, '')
  lines.push('---', '')

  if (brief) {
    lines.push('## Campaign Brief', '')
    if (brief.objective)       lines.push(`**Objective:** ${brief.objective}`, '')
    if (brief.audience)        lines.push(`**Audience:** ${brief.audience}`, '')
    if (brief.timeline)        lines.push(`**Timeline:** ${brief.timeline}`, '')
    if (brief.budgetGuidance)  lines.push(`**Budget guidance:** ${brief.budgetGuidance}`, '')
    if (brief.keyMessages?.length) {
      lines.push('### Key Messages', '')
      brief.keyMessages.forEach((m) => lines.push(`- ${m}`))
      lines.push('')
    }
    if (brief.kpis?.length) {
      lines.push('### KPIs', '')
      brief.kpis.forEach((k) => lines.push(`- ${k}`))
      lines.push('')
    }
    lines.push('---', '')
  }

  const channelsWithContent = Object.keys(packs).filter(
    (ch) => (packs[ch]?.captions?.length ?? 0) > 0 || (packs[ch]?.adCopy?.length ?? 0) > 0
  )
  if (channelsWithContent.length) {
    lines.push('## Content Packs', '')
    for (const ch of channelsWithContent) {
      const label = CHANNEL_LABELS[ch] ?? ch
      lines.push(`### ${CHANNEL_ICONS[ch] ?? ''} ${label}`, '')
      const pack = packs[ch]
      if (pack?.captions?.length) {
        lines.push('#### Captions', '')
        pack.captions.forEach((cap, i) => {
          lines.push(`**Caption ${i + 1}**`, '', cap.text, '')
          if (cap.hashtags?.length) {
            lines.push(cap.hashtags.map((h) => `#${h.replace(/^#/, '')}`).join(' '), '')
          }
        })
      }
      if (pack?.adCopy?.length) {
        lines.push('#### Ad Copy', '')
        pack.adCopy.forEach((v, i) => {
          lines.push(`**Variant ${i + 1}**`, '', `**Headline:** ${v.headline}`, '', v.body, '')
          if (v.cta) lines.push(`**CTA:** ${v.cta}`, '')
        })
      }
    }
  }

  return lines.join('\n')
}

function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function CampaignsPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const {
    campaigns, setCampaigns, removeCampaign, upsertCampaign,
    activeCampaign, setActiveCampaign,
    setCampaignGeneratorOpen,
  } = useAppStore()

  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!projectId) return
    setLoading(true)
    api.campaigns.list(projectId)
      .then(setCampaigns)
      .catch(() => toast.error('Failed to load campaigns'))
      .finally(() => setLoading(false))
  }, [projectId]) // eslint-disable-line react-hooks/exhaustive-deps

  async function handleDelete(campaign: Campaign) {
    try {
      await api.campaigns.delete(projectId, campaign.id)
      removeCampaign(campaign.id)
      if (activeCampaign?.id === campaign.id) setActiveCampaign(null)
      toast.success('Campaign deleted')
    } catch {
      toast.error('Failed to delete campaign')
    }
  }

  async function handleDuplicate(campaign: Campaign) {
    try {
      const copy = await api.campaigns.duplicate(projectId, campaign.id)
      upsertCampaign(copy)
      toast.success(`"${copy.name}" created`)
    } catch {
      toast.error('Failed to duplicate campaign')
    }
  }

  return (
    <div className="flex h-screen overflow-hidden">
      {/* Left column - campaign list */}
      <div className="w-80 shrink-0 border-r border-border flex flex-col bg-card">
        <div className="flex items-center justify-between px-5 py-4 border-b border-border shrink-0">
          <div className="flex items-center gap-2">
            <SidebarToggle />
            <div>
              <h1 className="font-semibold text-sm">Campaigns</h1>
              <p className="text-xs text-muted-foreground">{campaigns.length} campaign{campaigns.length !== 1 ? 's' : ''}</p>
            </div>
          </div>
          <button
            onClick={() => setCampaignGeneratorOpen(true)}
            className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-xs font-medium hover:opacity-90 transition-opacity"
          >
            <Plus className="w-3 h-3" />
            New
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-3 space-y-2">
          {loading && (
            <div className="space-y-2">
              {[1, 2, 3].map((i) => (
                <div key={i} className="h-20 rounded-xl bg-muted/40 animate-pulse" />
              ))}
            </div>
          )}

          {!loading && campaigns.length === 0 && (
            <div className="flex flex-col items-center justify-center py-16 text-center space-y-3">
              <Zap className="w-8 h-8 text-muted-foreground/30" />
              <p className="text-sm font-medium">No campaigns yet</p>
              <p className="text-xs text-muted-foreground max-w-xs">
                Generate a full campaign brief and content packs in seconds.
              </p>
              <button
                onClick={() => setCampaignGeneratorOpen(true)}
                className="mt-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-medium hover:opacity-90 transition-opacity"
              >
                Generate first campaign
              </button>
            </div>
          )}

          {!loading && campaigns.map((campaign) => (
            <div
              key={campaign.id}
              className={cn(
                'group relative rounded-xl border p-4 cursor-pointer transition-colors',
                activeCampaign?.id === campaign.id
                  ? 'border-primary/50 bg-primary/5'
                  : 'border-border bg-background hover:border-primary/30',
              )}
              onClick={() => setActiveCampaign(campaign)}
            >
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <p className="text-sm font-medium truncate">{campaign.name}</p>
                    <StatusBadge status={campaign.status} />
                  </div>
                  <p className="text-xs text-muted-foreground line-clamp-2">{campaign.objective}</p>
                  <div className="flex flex-wrap gap-1 mt-2">
                    {campaign.channels?.slice(0, 3).map((ch) => (
                      <span key={ch} className="text-xs bg-muted px-1.5 py-0.5 rounded-md">
                        {CHANNEL_ICONS[ch] ?? '📄'} {CHANNEL_LABELS[ch] ?? ch}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDuplicate(campaign) }}
                    className="p-1 rounded-md opacity-0 group-hover:opacity-100 text-muted-foreground hover:text-foreground transition-all"
                    title="Duplicate"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDelete(campaign) }}
                    className="p-1 rounded-md opacity-0 group-hover:opacity-100 text-muted-foreground hover:text-destructive transition-all"
                    title="Delete"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                  <ChevronRight className="w-4 h-4 text-muted-foreground/40" />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Right column - campaign detail */}
      <div className="flex-1 overflow-hidden">
        {activeCampaign
          ? <CampaignDetail
              key={activeCampaign.id}
              campaign={activeCampaign}
              projectId={projectId}
              onDelete={handleDelete}
              onSaved={upsertCampaign}
            />
          : <div className="flex flex-col items-center justify-center h-full text-center gap-3 text-muted-foreground">
              <Zap className="w-10 h-10 opacity-20" />
              <p className="text-sm">Select a campaign to view details</p>
            </div>
        }
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Campaign detail
// ---------------------------------------------------------------------------

function CampaignDetail({ campaign, projectId, onDelete, onSaved }: {
  campaign: Campaign
  projectId: string
  onDelete: (c: Campaign) => void
  onSaved: (c: Campaign) => void
}) {
  const [activeChannel, setActiveChannel] = useState<string | null>(
    campaign.channels?.[0] ?? null
  )
  const [edits, setEdits] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState(false)

  const brief = campaign.brief
  const packs = campaign.contentPacks ?? {}
  const channelsWithContent = Object.keys(packs).filter(
    (ch) => (packs[ch]?.captions?.length ?? 0) > 0 || (packs[ch]?.adCopy?.length ?? 0) > 0
  )

  const hasEdits = Object.keys(edits).length > 0

  async function saveEdits() {
    if (!hasEdits) return
    setSaving(true)
    try {
      const updatedPacks = JSON.parse(JSON.stringify(packs)) as typeof packs
      for (const [key, value] of Object.entries(edits)) {
        const [ch, type, idxStr] = key.split('-')
        const idx = parseInt(idxStr, 10)
        if (type === 'caption' && updatedPacks[ch]?.captions?.[idx]) {
          updatedPacks[ch].captions![idx].text = value
        } else if (type === 'headline' && updatedPacks[ch]?.adCopy?.[idx]) {
          updatedPacks[ch].adCopy![idx].headline = value
        } else if (type === 'body' && updatedPacks[ch]?.adCopy?.[idx]) {
          updatedPacks[ch].adCopy![idx].body = value
        }
      }
      const updated = await api.campaigns.update(projectId, campaign.id, { contentPacks: updatedPacks as Record<string, unknown> })
      onSaved(updated)
      setEdits({})
      toast.success('Campaign saved')
    } catch {
      toast.error('Failed to save changes')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-3 px-6 py-4 border-b border-border shrink-0">
        <div className="flex-1 min-w-0">
          <h2 className="font-semibold text-base truncate">{campaign.name}</h2>
          <StatusBadge status={campaign.status} />
        </div>
        {hasEdits && (
          <button
            onClick={saveEdits}
            disabled={saving}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-xs font-medium hover:opacity-90 disabled:opacity-50 transition-opacity"
          >
            {saving ? <div className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" /> : <Check className="w-3 h-3" />}
            Save changes
          </button>
        )}
        <button
          onClick={() => {
            const md = buildCampaignMarkdown(campaign)
            const slug = campaign.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
            downloadMarkdown(`${slug}-campaign.md`, md)
            toast.success('Campaign exported')
          }}
          title="Export as Markdown"
          className="p-1.5 rounded-md hover:bg-muted text-muted-foreground hover:text-foreground"
        >
          <Download className="w-4 h-4" />
        </button>
        <button
          onClick={() => onDelete(campaign)}
          className="p-1.5 rounded-md hover:bg-muted text-muted-foreground hover:text-destructive"
          title="Delete campaign"
        >
          <Trash2 className="w-4 h-4" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {/* Brief */}
        {brief && (
          <div className="space-y-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Campaign Brief</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <BriefRow icon={<Target className="w-3.5 h-3.5" />} label="Objective" value={brief.objective} />
              <BriefRow icon={<Users className="w-3.5 h-3.5" />} label="Audience" value={brief.audience} />
              <BriefRow icon={<Calendar className="w-3.5 h-3.5" />} label="Timeline" value={brief.timeline} />
              {brief.budgetGuidance && (
                <BriefRow icon={<BarChart2 className="w-3.5 h-3.5" />} label="Budget" value={brief.budgetGuidance} />
              )}
            </div>
            {brief.keyMessages?.length > 0 && (
              <div>
                <p className="text-xs text-muted-foreground mb-1.5 font-medium">Key messages</p>
                <ul className="space-y-1">
                  {brief.keyMessages.map((m, i) => (
                    <li key={i} className="text-xs flex gap-2">
                      <span className="text-primary shrink-0">•</span>
                      <span>{m}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {brief.kpis?.length > 0 && (
              <div>
                <p className="text-xs text-muted-foreground mb-1.5 font-medium">KPIs</p>
                <div className="flex flex-wrap gap-1.5">
                  {brief.kpis.map((k) => (
                    <span key={k} className="px-2 py-0.5 rounded-full bg-muted text-xs">{k}</span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Content packs */}
        {channelsWithContent.length > 0 && (
          <div className="space-y-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Content Packs</p>
            <div className="flex gap-1.5 overflow-x-auto pb-1 scrollbar-none">
              {channelsWithContent.map((ch) => (
                <button
                  key={ch}
                  onClick={() => setActiveChannel(ch)}
                  className={cn(
                    'shrink-0 flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors whitespace-nowrap',
                    activeChannel === ch
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-muted text-muted-foreground hover:text-foreground',
                  )}
                >
                  <span>{CHANNEL_ICONS[ch] ?? '📄'}</span>
                  <span>{CHANNEL_LABELS[ch] ?? ch}</span>
                </button>
              ))}
            </div>
            {activeChannel && packs[activeChannel] && (
              <ContentPackView
                channel={activeChannel}
                pack={packs[activeChannel]}
                campaignId={campaign.id}
                projectId={projectId}
                edits={edits}
                onEdit={(key, value) => setEdits((prev) => ({ ...prev, [key]: value }))}
              />
            )}
          </div>
        )}

        {campaign.status === 'generating' && (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
            Generating…
          </div>
        )}
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Content pack view - inline editing + save to library
// ---------------------------------------------------------------------------

function ContentPackView({
  channel, pack, campaignId, projectId, edits, onEdit,
}: {
  channel: string
  pack: CampaignContentPack
  campaignId: string
  projectId: string
  edits: Record<string, string>
  onEdit: (key: string, value: string) => void
}) {
  const captions = pack.captions ?? []
  const adCopy = pack.adCopy ?? []

  async function saveToLibrary(content: string, hashtags: string[], type: 'caption' | 'ad_copy') {
    try {
      await api.contentLibrary.save(projectId, {
        platform: channel,
        type,
        content,
        hashtags,
        metadata: { savedFromCampaign: campaignId },
        status: 'draft',
        tags: ['campaign'],
      })
      toast.success('Saved to library')
    } catch {
      toast.error('Failed to save to library')
    }
  }

  return (
    <div className="space-y-3">
      {captions.map((cap, i) => {
        const key = `${channel}-caption-${i}`
        const text = edits[key] ?? cap.text
        return (
          <EditableBlock
            key={i}
            editKey={key}
            edits={edits}
            copyText={text + (cap.hashtags.length ? '\n\n' + cap.hashtags.map((h) => `#${h}`).join(' ') : '')}
            onSaveToLibrary={() => saveToLibrary(text, cap.hashtags, 'caption')}
          >
            <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-1">Caption {i + 1}</p>
            <ContentEditableText editKey={key} value={text} edits={edits} onEdit={onEdit} />
            {cap.hashtags.length > 0 && (
              <p className="mt-1.5 text-xs text-primary/70">
                {cap.hashtags.map((h) => `#${h.replace(/^#/, '')}`).join(' ')}
              </p>
            )}
          </EditableBlock>
        )
      })}

      {adCopy.map((v, i) => {
        const headlineKey = `${channel}-headline-${i}`
        const bodyKey = `${channel}-body-${i}`
        const headline = edits[headlineKey] ?? v.headline
        const body = edits[bodyKey] ?? v.body
        const copyText = `Headline: ${headline}\n\n${body}${v.cta ? `\n\nCTA: ${v.cta}` : ''}`
        return (
          <EditableBlock
            key={i}
            editKey={headlineKey}
            edits={edits}
            copyText={copyText}
            onSaveToLibrary={() => saveToLibrary(body, [], 'ad_copy')}
          >
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Headline</p>
            <ContentEditableText editKey={headlineKey} value={headline} edits={edits} onEdit={onEdit} isOneLine />
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mt-1.5">Body</p>
            <ContentEditableText editKey={bodyKey} value={body} edits={edits} onEdit={onEdit} />
            {v.cta && (
              <>
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mt-1.5">CTA</p>
                <span className="inline-block px-2 py-0.5 rounded-md bg-primary/10 text-primary text-xs font-medium">{v.cta}</span>
              </>
            )}
          </EditableBlock>
        )
      })}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Editable block wrapper
// ---------------------------------------------------------------------------

function EditableBlock({
  children, editKey, edits, copyText, onSaveToLibrary,
}: {
  children: React.ReactNode
  editKey: string
  edits: Record<string, string>
  copyText: string
  onSaveToLibrary: () => void
}) {
  const isEdited = Object.keys(edits).some((k) => k.startsWith(editKey.split('-').slice(0, 2).join('-')))
  return (
    <div className={cn(
      'group relative rounded-lg border bg-background p-3',
      isEdited ? 'border-primary/50' : 'border-border',
    )}>
      {children}
      <div className="absolute top-2.5 right-2.5 flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <button
          onClick={onSaveToLibrary}
          className="p-1.5 rounded-md bg-muted hover:bg-muted/80 text-muted-foreground hover:text-primary"
          title="Save to library"
        >
          <BookmarkPlus className="w-3 h-3" />
        </button>
        <CopyBtn text={copyText} />
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Inline editable text
// ---------------------------------------------------------------------------

function ContentEditableText({
  editKey, value, edits, onEdit, isOneLine = false,
}: {
  editKey: string
  value: string
  edits: Record<string, string>
  onEdit: (key: string, value: string) => void
  isOneLine?: boolean
}) {
  const [editing, setEditing] = useState(false)

  if (!editing) {
    return (
      <div className="flex items-start gap-1 group/text">
        <p className={cn('text-sm leading-relaxed flex-1', isOneLine && 'font-medium')}>{value}</p>
        <button
          onClick={() => setEditing(true)}
          className="p-0.5 rounded opacity-0 group-hover/text:opacity-100 text-muted-foreground hover:text-foreground transition-opacity shrink-0 mt-0.5"
          title="Edit"
        >
          <Pencil className="w-2.5 h-2.5" />
        </button>
      </div>
    )
  }

  return (
    <textarea
      autoFocus
      rows={isOneLine ? 1 : 4}
      value={edits[editKey] ?? value}
      onChange={(e) => onEdit(editKey, e.target.value)}
      onBlur={() => setEditing(false)}
      className="w-full text-sm leading-relaxed bg-muted/40 border border-primary/30 rounded-md p-2 focus:outline-none resize-none"
    />
  )
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function BriefRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  if (!value) return null
  return (
    <div className="flex gap-3">
      <span className="text-muted-foreground shrink-0 mt-0.5">{icon}</span>
      <div>
        <p className="text-[11px] text-muted-foreground font-medium mb-0.5">{label}</p>
        <p className="text-sm">{value}</p>
      </div>
    </div>
  )
}

function StatusBadge({ status }: { status: Campaign['status'] }) {
  if (status === 'ready') return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full bg-green-500/10 text-green-600 dark:text-green-400 text-[10px] font-medium">
      Ready
    </span>
  )
  if (status === 'generating') return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full bg-primary/10 text-primary text-[10px] font-medium">
      Generating…
    </span>
  )
  return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full bg-destructive/10 text-destructive text-[10px] font-medium">
      Error
    </span>
  )
}

function CopyBtn({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  function copy(e: React.MouseEvent) {
    e.stopPropagation()
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }
  return (
    <button
      onClick={copy}
      className="p-1.5 rounded-md bg-muted hover:bg-muted/80 text-muted-foreground hover:text-foreground transition-all"
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
    </button>
  )
}
